import type { Metadata } from "next";
import { Inter, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/Navbar";
import LenisProvider from "./components/LenisProvider";
import Footer from "./components/navigation/Footer";

const stack = Stack_Sans_Notch({
  variable: "--font-headlines",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className={`${stack.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
